### ISSUE TITLE
Problem of update deletion

### ISSUE THREAD

**Issue by TheoRudkiewicz** [growingnet/gromo#6]
If you use the method `delete_update` on modules you can have an error when using `.extended_forward`.

If you have an architecture L1 -> L2 with an output extension of L1 and input extension of L2 the extended forward works. But if you apply delete update on only one of the two you will break the extended forward.

Possible fix:
- remove `self.extended_output_layer = None`
- in addition when we handle the previous  module output deletion we could check carefully that the deletion correctly happens.

**Comment by sylvchev** [comment]
I'm missing the use cases of `delete_update`, is this method called often and on what purpose?

I'm more in favor of the second solution, starting by the fact that when we connect layers, the output extension of L1 and input extension of L2 should be correctly positionned and we could explicitely test this.

**Comment by sylvchev** [comment]
I'll guess it comes back to.whom decide the best update to keep, this entity should also be responsible to delete unused update. What do you think?

**Comment by streethagore** [comment]
I see that `delete_update` is used within the `select_update` and `select_best_update` functions. Is it used anywhere else ?
If not, then `select_update` and `select_best_update` should be responsible for correctly deleting the updates in different layers.

**Comment by streethagore** [comment]
If I replace [this line](https://github.com/growingnet/gromo/blob/139662a7ca99c5520e230b9ac9b122efc4fee1ab/src/gromo/growing_mlp.py#L204) by "if i not in [layer_index - 1, layer_index]:"
The script mlp_runs.py runs for me.
However, I am not sure if computations are properly deleted after the update.
I would expect the function `apply_update` to handle the deletion of the update, with an optional flag to prevent from erasing the statistics if we need to dig into them.

What's your thoughts ?

**Comment by TheoRudkiewicz** [comment]
> If I replace [this line](https://github.com/growingnet/gromo/blob/139662a7ca99c5520e230b9ac9b122efc4fee1ab/src/gromo/growing_mlp.py#L204) by "if i not in [layer_index - 1, layer_index]:" The script mlp_runs.py runs for me. However, I am not sure if computations are properly deleted after the update. I would expect the function `apply_update` to handle the deletion of the update, with an optional flag to prevent from erasing the statistics if we need to dig into them.
> 
> What's your thoughts ?

Here I think that as you do not delete the `optimal_delta_layer` of layer `layer_index - 1` (i think) you do a natural gradient step in two different layers. This does not lead to a bug. however it is not the intended behavior.

**Comment by TheoRudkiewicz** [comment]
> I see that `delete_update` is used within the `select_update` and `select_best_update` functions. Is it used anywhere else ? If not, then `select_update` and `select_best_update` should be responsible for correctly deleting the updates in different layers.

I think we should suppose that a user may use the `LinearGrowingModule` without the wrappers like `GrowingMLP`. Hence the problem should be fixed directly in `GrowingModule`.
